# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
# Import pandas 
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
y=data.target

In [6]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [0]:
X=data.data

In [8]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
random_state=2
test_size=0.25
X_train,X_test,Y_train,Y_test=train_test_split(X,y,random_state=random_state,test_size=test_size)

In [10]:
print('X_train',X_train.shape)
print('X_test',X_test.shape)
print('Y_train',Y_train.shape)
print('Y_test',Y_test.shape)

X_train (112, 4)
X_test (38, 4)
Y_train (112,)
Y_test (38,)


## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [11]:
Y_train[0:10]

array([1, 2, 1, 1, 2, 1, 0, 2, 0, 1])

In [0]:
Y_train=pd.get_dummies(Y_train)

In [13]:
Y_train[0:10]

0  1  2
0  0  1  0
1  0  0  1
2  0  1  0
3  0  1  0
4  0  0  1
5  0  1  0
6  1  0  0
7  0  0  1
8  1  0  0
9  0  1  0

In [14]:
Y_test[0:10]

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0])

In [0]:
Y_test=pd.get_dummies(Y_test)

In [16]:
Y_test[0:10]

0  1  2
0  1  0  0
1  1  0  0
2  0  0  1
3  1  0  0
4  1  0  0
5  0  0  1
6  1  0  0
7  0  0  1
8  0  0  1
9  1  0  0

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
# Import `Sequential` from `keras.models`
from tensorflow.keras import layers

In [0]:
# Initialize the constructor
model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
# Add an input layer 
model.add(layers.Dense(3, activation='sigmoid',input_shape=(4,)))

# Add an output layer 
model.add(layers.Dense(3, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(loss='categorical_crossentropy',
              optimizer='SGD',
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 12        
Total params: 27
Trainable params: 27
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [22]:
features=X_train
label=Y_train
model.fit(features, label,epochs=100, batch_size=1, verbose=1)

Train on 112 samples
Epoch 1/100
112/112 [==============================] - 1s 6ms/sample - loss: 0.9587 - accuracy: 0.5804
Epoch 2/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.8774 - accuracy: 0.6518
Epoch 3/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.8312 - accuracy: 0.6786
Epoch 4/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.7924 - accuracy: 0.6607
Epoch 5/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.7562 - accuracy: 0.7143
Epoch 6/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.7255 - accuracy: 0.6786
Epoch 7/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.6978 - accuracy: 0.7054
Epoch 8/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.6742 - accuracy: 0.6964
Epoch 9/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.6535 - accuracy: 0.7946
Epoch 10/100
112/112 [==============================

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
y_pred = np.round(model.predict(X_test))

In [0]:
Y_pred=y_pred.argmax(axis=-1)

In [25]:
Y_pred

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 1])

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [0]:
Y_actual=Y_test.argmax(axis=-1)

In [28]:
Y_actual

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 1])

In [0]:
Y_test=np.array(Y_test)

In [29]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_actual,Y_pred))

1.0




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

In [0]:
import io
df_price = pd.read_csv('/content/prices.csv')

In [0]:
df_price.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
df_price.drop(['date','symbol'],axis=1,inplace=True)

In [0]:
df_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38145 entries, 0 to 38144
Data columns (total 5 columns):
open      38145 non-null float64
close     38145 non-null float64
low       38145 non-null float64
high      38144 non-null float64
volume    38144 non-null float64
dtypes: float64(5)
memory usage: 1.5 MB


## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
df_price_mod=pd.DataFrame(df_price.iloc[:1000,:])

In [0]:
df_price_mod.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
label=df_price_mod['volume']
features=df_price_mod.iloc[:,:-1]

In [0]:
features.shape

(1000, 4)

In [0]:
label.shape

(1000,)

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
label=np.array(label)

In [0]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
open     1000 non-null float64
close    1000 non-null float64
low      1000 non-null float64
high     1000 non-null float64
dtypes: float64(4)
memory usage: 31.4 KB


In [0]:
features=features.astype('float32')

In [0]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
open     1000 non-null float32
close    1000 non-null float32
low      1000 non-null float32
high     1000 non-null float32
dtypes: float32(4)
memory usage: 15.8 KB


In [0]:
features=np.array(features)

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X=tf.math.l2_normalize(
    features,
    axis=None,
    epsilon=1e-12,
    name=None
)


## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.zeros(shape=(4, 1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def prediction(features, W, b):
  y_pred = tf.add(tf.matmul(features, W), b)    
  return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
def loss(y_actual, y_predicted):
  diff = y_actual - y_predicted
  sqr = tf.square(diff)     
  avg = tf.reduce_mean(sqr)     
  return avg 

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
  # Record mathematical operations on 'tape' to calculate loss     
   with tf.GradientTape() as t:         
     t.watch([w,b])         
     current_prediction = prediction(x, w, b)
     current_loss = loss(y_actual, current_prediction)
     # Calculate Gradients for Loss with respect to Weights and Bias    
     dw, db = t.gradient(current_loss,[w, b])          
     # Update Weights and Bias     
     w = w - learning_rate * dw     
     b = b - learning_rate * db          
     return w, b 

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [0]:
for i in range(100):
  W, b = train(X, y, W, b)
  print('Current Training Loss on iteration', i, loss(y, prediction(X, W, b)).numpy())

Current Training Loss on iteration 0 0.6835192
Current Training Loss on iteration 1 0.6828516
Current Training Loss on iteration 2 0.6822101
Current Training Loss on iteration 3 0.6815942
Current Training Loss on iteration 4 0.68100274
Current Training Loss on iteration 5 0.68043447
Current Training Loss on iteration 6 0.6798891
Current Training Loss on iteration 7 0.67936534
Current Training Loss on iteration 8 0.678862
Current Training Loss on iteration 9 0.6783792
Current Training Loss on iteration 10 0.6779151
Current Training Loss on iteration 11 0.6774691
Current Training Loss on iteration 12 0.6770411
Current Training Loss on iteration 13 0.6766301
Current Training Loss on iteration 14 0.6762353
Current Training Loss on iteration 15 0.6758562
Current Training Loss on iteration 16 0.67549217
Current Training Loss on iteration 17 0.6751423
Current Training Loss on iteration 18 0.67480654
Current Training Loss on iteration 19 0.67448425
Current Training Loss on iteration 20 0.67417

### Observe values of Weight
- Print the updated values

In [0]:
print(W)

tf.Tensor(
[[0.01166533]
 [0.01168646]
 [0.01154703]
 [0.01178214]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [0]:
print(b)

tf.Tensor([0.9818968], shape=(1,), dtype=float32)
